'use server'

import { prisma, PaymentMethodEnum, PaymentStatusEnum } from '@kms/database'
import { revalidatePath } from 'next/cache'

export async function generateInstancesForEnrollment(enrollmentId: string) {
    try {
        const enrollment = await prisma.enrollment.findUnique({
            where: { id: enrollmentId },
            include: {
                feePackage: true,
                monthlyFeeInstances: { include: { payments: true } },
                miscFees: { include: { payments: true } },
            }
        });

        if (!enrollment || !enrollment.feePackage) return { success: false, error: 'Valid enrollment and fee package required.' };

        // We use the existing getFeePreviewData function to calculate the exact line costs for the current state
        const { getFeePreviewData } = await import('../students/fee-preview-actions');
        const previewRes = await getFeePreviewData(enrollmentId);
        if (!previewRes.success || !previewRes.data) return { success: false, error: 'Could not calculate fee preview.' };

        const { oneTimeFees, monthlyFees } = previewRes.data;

        await prisma.$transaction(async (tx) => {
            // Delete obsolete non-adhoc one-time fees
            // If the fee was generated by a previous package but is no longer in the current oneTimeFees, we wipe it (if unpaid).
            const validOneTimeNames = oneTimeFees.map(f => f.name);
            const obsoleteMiscFeeIds = enrollment.miscFees
                .filter(m => !m.isAdhoc && !validOneTimeNames.includes(m.name) && m.payments.length === 0)
                .map(m => m.id);

            if (obsoleteMiscFeeIds.length > 0) {
                await tx.miscFee.deleteMany({
                    where: { id: { in: obsoleteMiscFeeIds } }
                });
            }

            // Sync ONE_TIME fees
            for (const item of oneTimeFees) {
                const existing = enrollment.miscFees.find(m => m.name === item.name);
                if (!existing) {
                    const status = item.finalLineCost <= 0 ? PaymentStatusEnum.PAID : PaymentStatusEnum.UNPAID;
                    await tx.miscFee.create({
                        data: {
                            enrollmentId,
                            name: item.name,
                            amountDue: item.finalLineCost,
                            status
                        }
                    });
                } else {
                    const totalPaid = existing.payments.reduce((sum: number, p: any) => sum + p.amountPaid, 0);

                    // HISTORICAL LOCK: If any money has been paid towards this one-time item, do NOT overwrite its amountDue or status.
                    if (totalPaid > 0) {
                        continue;
                    }

                    let status: PaymentStatusEnum = PaymentStatusEnum.UNPAID;
                    if (item.finalLineCost <= 0) status = PaymentStatusEnum.PAID;

                    if (existing.amountDue !== item.finalLineCost || existing.status !== status) {
                        await tx.miscFee.update({
                            where: { id: existing.id },
                            data: { amountDue: item.finalLineCost, status }
                        });
                    }
                }
            }

            // Sync MONTHLY fees
            const TOTAL_MONTHS = 11;
            const startMonth = enrollment.startDate ? enrollment.startDate.getMonth() + 1 : 1;
            const effectiveStartMonth = Math.min(startMonth, TOTAL_MONTHS);

            // Delete obsolete generated months (e.g. if start date moved from Jan to June, months 1-5 are obsolete)
            const obsoleteInstanceIds = enrollment.monthlyFeeInstances
                .filter(m => m.month < effectiveStartMonth && m.payments.length === 0)
                .map(m => m.id);

            if (obsoleteInstanceIds.length > 0) {
                await tx.monthlyFeeInstance.deleteMany({
                    where: { id: { in: obsoleteInstanceIds } }
                });
            }

            for (const item of monthlyFees) {
                for (let month = effectiveStartMonth; month <= TOTAL_MONTHS; month++) {
                    const existing = enrollment.monthlyFeeInstances.find(m => m.feeItemId === item.feeItemId && m.month === month);
                    if (!existing) {
                        const status = item.finalLineCost <= 0 ? PaymentStatusEnum.PAID : PaymentStatusEnum.UNPAID;
                        await tx.monthlyFeeInstance.create({
                            data: {
                                enrollmentId,
                                feeItemId: item.feeItemId,
                                month,
                                amountDue: item.finalLineCost,
                                status
                            }
                        });
                    } else {
                        const totalPaid = existing.payments.reduce((sum: number, p: any) => sum + p.amountPaid, 0);

                        // HISTORICAL LOCK: If any money has been paid towards this month, do NOT overwrite its amountDue or status.
                        // This prevents Programme Switches from corrupting past paid months turning them into "Partial".
                        if (totalPaid > 0) {
                            continue;
                        }

                        let status: PaymentStatusEnum = PaymentStatusEnum.UNPAID;
                        if (item.finalLineCost <= 0) status = PaymentStatusEnum.PAID;

                        if (existing.amountDue !== item.finalLineCost || existing.status !== status) {
                            await tx.monthlyFeeInstance.update({
                                where: { id: existing.id },
                                data: { amountDue: item.finalLineCost, status }
                            });
                        }
                    }
                }
            }
        });

        return { success: true };
    } catch (error: any) {
        console.error('Generation Error:', error);
        return { success: false, error: error.message };
    }
}

export async function logPayment(data: {
    enrollmentId: string;
    amountPaid: number;
    method: PaymentMethodEnum;
    note?: string;
    monthlyFeeInstanceId?: string;
    bookInstanceId?: string;
    miscFeeId?: string;
}) {
    try {
        await prisma.$transaction(async (tx) => {
            // 1. Create the payment
            const payment = await tx.payment.create({
                data: {
                    enrollmentId: data.enrollmentId,
                    amountPaid: data.amountPaid,
                    method: data.method,
                    note: data.note,
                    paidAt: new Date(),
                    monthlyFeeInstanceId: data.monthlyFeeInstanceId,
                    bookInstanceId: data.bookInstanceId,
                    miscFeeId: data.miscFeeId
                }
            });

            // 2. Recalculate status of the instance
            if (data.monthlyFeeInstanceId) {
                const instance = await tx.monthlyFeeInstance.findUnique({
                    where: { id: data.monthlyFeeInstanceId },
                    include: { payments: true }
                });
                if (instance) {
                    const totalPaid = instance.payments.reduce((sum, p) => sum + p.amountPaid, 0);
                    const status = totalPaid >= instance.amountDue ? PaymentStatusEnum.PAID :
                        totalPaid > 0 ? PaymentStatusEnum.PARTIAL : PaymentStatusEnum.UNPAID;
                    await tx.monthlyFeeInstance.update({
                        where: { id: instance.id },
                        data: { status }
                    });
                }
            } else if (data.bookInstanceId) {
                const instance = await tx.bookInstance.findUnique({
                    where: { id: data.bookInstanceId },
                    include: { payments: true }
                });
                if (instance) {
                    const totalPaid = instance.payments.reduce((sum, p) => sum + p.amountPaid, 0);
                    const status = totalPaid >= instance.amountDue ? PaymentStatusEnum.PAID :
                        totalPaid > 0 ? PaymentStatusEnum.PARTIAL : PaymentStatusEnum.UNPAID;
                    await tx.bookInstance.update({
                        where: { id: instance.id },
                        data: { status }
                    });
                }
            } else if (data.miscFeeId) {
                const instance = await tx.miscFee.findUnique({
                    where: { id: data.miscFeeId },
                    include: { payments: true }
                });
                if (instance) {
                    const totalPaid = instance.payments.reduce((sum, p) => sum + p.amountPaid, 0);
                    const status = totalPaid >= instance.amountDue ? PaymentStatusEnum.PAID :
                        totalPaid > 0 ? PaymentStatusEnum.PARTIAL : PaymentStatusEnum.UNPAID;
                    await tx.miscFee.update({
                        where: { id: instance.id },
                        data: { status }
                    });
                }
            }
        });

        revalidatePath('/admin/payments');
        return { success: true };
    } catch (error: any) {
        console.error('Payment Error:', error);
        return { success: false, error: error.message };
    }
}

export async function createAdhocCharge(data: { enrollmentId: string; name: string; amountDue: number }) {
    try {
        if (!data.name || data.amountDue <= 0) {
            throw new Error("Invalid charge details");
        }

        await prisma.miscFee.create({
            data: {
                enrollmentId: data.enrollmentId,
                name: data.name,
                amountDue: data.amountDue,
                status: PaymentStatusEnum.UNPAID,
                isAdhoc: true
            }
        });

        revalidatePath('/admin/payments');
        revalidatePath(`/admin/payments/${data.enrollmentId}`);
        return { success: true };
    } catch (error: any) {
        console.error('Adhoc Charge Error:', error);
        return { success: false, error: error.message };
    }
}

export async function getDashboardData(year: number) {
    try {
        const enrollments = await prisma.enrollment.findMany({
            where: { academicYear: year, status: 'ACTIVE' },
            include: {
                student: true,
                feePackage: true,
                monthlyFeeInstances: { include: { payments: true } },
                bookInstances: { include: { payments: true } },
                miscFees: { include: { payments: true } }
            }
        });

        const dashboardRows = enrollments.map(enrol => {
            let startupDue = 0;
            let startupPaid = 0;
            let startupUnpaidCount = 0;
            let startupPartialCount = 0;

            let miscDue = 0;
            let miscPaid = 0;
            let miscUnpaidCount = 0;
            let miscPartialCount = 0;

            const processInstances = (
                instances: any[],
                isMisc: boolean = false
            ) => {
                instances.forEach(inst => {
                    const instPaid = inst.payments.reduce((sum: number, p: any) => sum + p.amountPaid, 0);

                    // If it's the miscFees array, check the isAdhoc flag
                    if (isMisc && inst.isAdhoc) {
                        miscDue += inst.amountDue;
                        miscPaid += instPaid;
                        if (inst.status === PaymentStatusEnum.UNPAID) miscUnpaidCount++;
                        else if (inst.status === PaymentStatusEnum.PARTIAL) miscPartialCount++;
                    } else {
                        // Startup fees are bookInstances OR non-adhoc miscFees
                        startupDue += inst.amountDue;
                        startupPaid += instPaid;
                        if (inst.status === PaymentStatusEnum.UNPAID) startupUnpaidCount++;
                        else if (inst.status === PaymentStatusEnum.PARTIAL) startupPartialCount++;
                    }
                });
            };

            processInstances(enrol.bookInstances);
            processInstances(enrol.miscFees, true);

            let startupStatus: PaymentStatusEnum = PaymentStatusEnum.PAID;
            if (startupUnpaidCount > 0 && startupPaid > 0) startupStatus = PaymentStatusEnum.PARTIAL;
            else if (startupUnpaidCount > 0 && startupPaid === 0) startupStatus = PaymentStatusEnum.UNPAID;
            else if (startupPartialCount > 0) startupStatus = PaymentStatusEnum.PARTIAL;
            else if (startupDue === 0 && startupPaid === 0) startupStatus = PaymentStatusEnum.UNPAID;

            let miscStatus: PaymentStatusEnum = PaymentStatusEnum.PAID;
            if (miscUnpaidCount > 0 && miscPaid > 0) miscStatus = PaymentStatusEnum.PARTIAL;
            else if (miscUnpaidCount > 0 && miscPaid === 0) miscStatus = PaymentStatusEnum.UNPAID;
            else if (miscPartialCount > 0) miscStatus = PaymentStatusEnum.PARTIAL;
            else if (miscDue === 0 && miscPaid === 0) miscStatus = PaymentStatusEnum.UNPAID;

            // Monthly Fees processing (months 1 to 11 typically)
            // We'll create a simple map of month -> status
            const monthlyGrid: Record<number, PaymentStatusEnum> = {};
            let monthlyDue = 0;
            let monthlyPaid = 0;

            enrol.monthlyFeeInstances.forEach(inst => {
                monthlyDue += inst.amountDue;
                monthlyPaid += inst.payments.reduce((sum: number, p: any) => sum + p.amountPaid, 0);

                // If it's the same month but multiple items, get the "worst" status
                const existing = monthlyGrid[inst.month];
                if (!existing) {
                    monthlyGrid[inst.month] = inst.status;
                } else {
                    if (inst.status === PaymentStatusEnum.UNPAID) monthlyGrid[inst.month] = PaymentStatusEnum.UNPAID;
                    else if (inst.status === PaymentStatusEnum.PARTIAL && existing === PaymentStatusEnum.PAID) {
                        monthlyGrid[inst.month] = PaymentStatusEnum.PARTIAL;
                    }
                }
            });

            // Flatten grid into an array of strictly 11 months for UI consistency, or just up to the max month generated
            const monthlyStatuses = Array.from({ length: 11 }, (_, i) => {
                return { month: i + 1, status: monthlyGrid[i + 1] || null }; // null means no fee for that month
            });

            // Overall Status for filtering/sorting
            let overallStatus: PaymentStatusEnum = PaymentStatusEnum.PAID;
            const totalDue = startupDue + miscDue + monthlyDue;
            const totalPaid = startupPaid + miscPaid + monthlyPaid;
            if (totalDue > 0 && totalPaid === 0) overallStatus = PaymentStatusEnum.UNPAID;
            else if (totalDue > 0 && totalPaid < totalDue) overallStatus = PaymentStatusEnum.PARTIAL;

            return {
                enrollmentId: enrol.id,
                studentId: enrol.student.id,
                studentName: enrol.student.name,
                level: enrol.enrollmentLevel,
                program: enrol.programType,
                startupDue,
                startupPaid,
                startupOutstanding: Math.max(0, startupDue - startupPaid),
                startupStatus,
                miscDue,
                miscPaid,
                miscOutstanding: Math.max(0, miscDue - miscPaid),
                miscStatus,
                monthlyDue,
                monthlyPaid,
                monthlyStatuses,
                status: overallStatus
            };
        });

        return { success: true, data: dashboardRows };
    } catch (error: any) {
        console.error('Fetch Error:', error);
        return { success: false, error: error.message };
    }
}

export async function getEnrollmentPaymentDetails(enrollmentId: string) {
    try {
        const enrollment = await prisma.enrollment.findUnique({
            where: { id: enrollmentId },
            include: {
                student: true,
                feePackage: true,
                class: true,
                monthlyFeeInstances: {
                    include: {
                        feeItem: true,
                        payments: { orderBy: { createdAt: 'desc' } }
                    },
                    orderBy: { month: 'asc' }
                },
                bookInstances: {
                    include: {
                        feeItem: true,
                        payments: { orderBy: { createdAt: 'desc' } }
                    }
                },
                miscFees: {
                    include: {
                        payments: { orderBy: { createdAt: 'desc' } }
                    }
                }
            }
        });

        if (!enrollment) return { success: false, error: 'Enrollment not found' };

        return { success: true, data: enrollment };
    } catch (error: any) {
        console.error('Fetch Details Error:', error);
        return { success: false, error: error.message };
    }
}

export async function logLumpsumPayment(data: {
    enrollmentId: string;
    amountPaid: number;
    method: PaymentMethodEnum;
    note?: string;
}) {
    try {
        if (data.amountPaid <= 0) {
            throw new Error("Amount must be greater than zero");
        }

        // 1. Fetch data OUTSIDE the transaction to prevent long-running transaction timeouts
        const enrollment = await prisma.enrollment.findUnique({
            where: { id: data.enrollmentId },
            include: {
                monthlyFeeInstances: {
                    include: { payments: true },
                    orderBy: { month: 'asc' }
                },
                bookInstances: {
                    include: { payments: true }
                },
                miscFees: {
                    where: { isAdhoc: false },
                    include: { payments: true }
                }
            }
        });

        if (!enrollment) throw new Error("Enrollment not found");

        // Build a list of items to pay off
        const payableItems: Array<{
            id: string;
            type: 'MONTHLY' | 'BOOK' | 'MISC';
            name: string;
            outstanding: number;
            priority: number;
        }> = [];

        // 2. All Monthly fees (dynamic priority)
        const firstMonth = enrollment.monthlyFeeInstances.length > 0 ? enrollment.monthlyFeeInstances[0].month : 1;
        for (const inst of enrollment.monthlyFeeInstances) {
            const paid = inst.payments.reduce((s, p) => s + p.amountPaid, 0);
            const outstanding = Math.max(0, inst.amountDue - paid);
            if (outstanding > 0) {
                let priority: number;
                if (inst.month === firstMonth) {
                    priority = 1; // Prioritize first month alongside start-up fees
                } else {
                    priority = 5 + inst.month; // Subsequent months cascade priorities
                }

                payableItems.push({
                    id: inst.id,
                    type: 'MONTHLY',
                    name: `Month ${inst.month}`,
                    outstanding,
                    priority
                });
            }
        }

        // 3. Other fees
        for (const misc of enrollment.miscFees) {
            const paid = misc.payments.reduce((s, p) => s + p.amountPaid, 0);
            const outstanding = Math.max(0, misc.amountDue - paid);
            if (outstanding > 0) {
                let priority = 4;
                const lowerName = misc.name.toLowerCase();
                if (lowerName.includes('deposit')) priority = 2;
                else if (lowerName.includes('registration')) priority = 3;

                payableItems.push({
                    id: misc.id,
                    type: 'MISC',
                    name: misc.name,
                    outstanding,
                    priority
                });
            }
        }

        // Sort by priority (1 to 4)
        payableItems.sort((a, b) => a.priority - b.priority);

        let remainingAmount = data.amountPaid;

        // 4. Perform the updates inside a transaction
        await prisma.$transaction(async (tx) => {
            const operations = [];

            for (const item of payableItems) {
                if (remainingAmount <= 0) break;

                const amountToApply = Math.min(item.outstanding, remainingAmount);
                remainingAmount -= amountToApply;

                // Create payment
                operations.push(
                    tx.payment.create({
                        data: {
                            enrollmentId: data.enrollmentId,
                            amountPaid: amountToApply,
                            method: data.method,
                            note: data.note ? `Lumpsum: ${data.note}` : `Lumpsum Payment Distribution`,
                            paidAt: new Date(),
                            monthlyFeeInstanceId: item.type === 'MONTHLY' ? item.id : null,
                            miscFeeId: item.type === 'MISC' ? item.id : null,
                        }
                    })
                );

                // Update status of the respective item
                const newOutstanding = item.outstanding - amountToApply;
                const newStatus = newOutstanding <= 0 ? PaymentStatusEnum.PAID : PaymentStatusEnum.PARTIAL;

                if (item.type === 'MONTHLY') {
                    operations.push(
                        tx.monthlyFeeInstance.update({
                            where: { id: item.id },
                            data: { status: newStatus }
                        })
                    );
                } else if (item.type === 'MISC') {
                    operations.push(
                        tx.miscFee.update({
                            where: { id: item.id },
                            data: { status: newStatus }
                        })
                    );
                }
            }

            await Promise.all(operations);
        });

        // We do not throw error if remainingAmount > 0 for now (it floats or is just overpaid), 
        // but for safety we just process what we can. 

        revalidatePath('/admin/payments');
        revalidatePath(`/admin/payments/${data.enrollmentId}`);
        return { success: true };
    } catch (error: any) {
        console.error('Lumpsum Payment Error:', error);
        return { success: false, error: error.message };
    }
}

export async function applyMonthlyFeeAdjustment({
    enrollmentId,
    feeItemCode = "MONTHLY_FEE",
    months,
    type,
    percent,
    fixedAmount,
    reason,
    adjustedBy
}: {
    enrollmentId: string;
    feeItemCode?: string;
    months: number[];
    type: "WAIVE" | "PERCENT" | "FIXED_AMOUNT";
    percent?: number;
    fixedAmount?: number;
    reason: string;
    adjustedBy?: string;
}) {
    try {
        const feeItem = await prisma.feeItem.findUnique({
            where: { code: feeItemCode }
        });

        if (!feeItem) throw new Error(`FeeItem ${feeItemCode} not found.`);

        const validMonths = months.map(m => Number(m));

        const instances = await prisma.monthlyFeeInstance.findMany({
            where: {
                enrollmentId,
                feeItemId: feeItem.id,
                month: { in: validMonths }
            },
            include: { payments: true }
        });

        const adjustedMonths: Record<number, number> = {};
        const lockedMonths: number[] = [];

        await prisma.$transaction(async (tx) => {
            const updatePromises = [];
            for (const instance of instances) {
                if (instance.payments.length > 0) {
                    lockedMonths.push(instance.month);
                    continue;
                }

                const originalAmountDue = (instance as any).originalAmountDue ?? instance.amountDue;
                let newAmountDue = originalAmountDue;
                let newStatus = instance.status === "UNPAID" ? instance.status : "UNPAID"; // Default re-calc if reverting waived

                if (type === "WAIVE") {
                    newAmountDue = 0;
                    newStatus = 'WAIVED' as any; // Cast for Prisma schema extension safely
                } else if (type === "PERCENT") {
                    if (percent === undefined) throw new Error("Percent is required for PERCENT adjustment");
                    newAmountDue = Math.round((originalAmountDue * (percent / 100)) * 100) / 100;
                    newStatus = 'UNPAID' as any;
                } else if (type === "FIXED_AMOUNT") {
                    if (fixedAmount === undefined) throw new Error("Fixed amount is required for FIXED_AMOUNT adjustment");
                    newAmountDue = fixedAmount;
                    newStatus = 'UNPAID' as any;
                }

                updatePromises.push(
                    tx.monthlyFeeInstance.update({
                        where: { id: instance.id },
                        data: {
                            originalAmountDue,
                            amountDue: newAmountDue,
                            status: newStatus as any,
                            adjustmentType: type as any,
                            adjustmentPercent: type === "PERCENT" ? percent : null,
                            adjustmentFixedAmount: type === "FIXED_AMOUNT" ? fixedAmount : null,
                            adjustmentReason: reason,
                            adjustedAt: new Date(),
                            adjustedBy
                        } as any
                    })
                );

                adjustedMonths[instance.month] = newAmountDue;
            }
            await Promise.all(updatePromises);
        }, { maxWait: 5000, timeout: 20000 });

        revalidatePath(`/admin/payments`);
        revalidatePath(`/admin/payments/${enrollmentId}`);

        return { success: true, adjustedMonths, lockedMonths };
    } catch (error: any) {
        console.error('applyMonthlyFeeAdjustment error:', error);
        return { success: false, error: error.message };
    }
}

export async function restoreMonthlyFeeAmount({
    enrollmentId,
    feeItemCode = "MONTHLY_FEE",
    months,
    reason,
    adjustedBy
}: {
    enrollmentId: string;
    feeItemCode?: string;
    months: number[];
    reason: string;
    adjustedBy?: string;
}) {
    try {
        const feeItem = await prisma.feeItem.findUnique({
            where: { code: feeItemCode }
        });

        if (!feeItem) throw new Error(`FeeItem ${feeItemCode} not found.`);

        const validMonths = months.map(m => Number(m));

        const instances = await prisma.monthlyFeeInstance.findMany({
            where: {
                enrollmentId,
                feeItemId: feeItem.id,
                month: { in: validMonths }
            },
            include: { payments: true }
        });

        const restoredMonths: number[] = [];
        const lockedMonths: number[] = [];

        await prisma.$transaction(async (tx) => {
            const updatePromises = [];
            for (const instance of instances) {
                if (instance.payments.length > 0) {
                    lockedMonths.push(instance.month);
                    continue;
                }

                if ((instance as any).originalAmountDue === null) {
                    continue; // Nothing to restore
                }

                updatePromises.push(
                    tx.monthlyFeeInstance.update({
                        where: { id: instance.id },
                        data: {
                            amountDue: (instance as any).originalAmountDue,
                            status: 'UNPAID' as any,
                            adjustmentType: null,
                            adjustmentPercent: null,
                            adjustmentFixedAmount: null,
                            adjustmentReason: `RESTORED: ${reason}`,
                            adjustedAt: new Date(),
                            adjustedBy
                        } as any
                    })
                );

                restoredMonths.push(instance.month);
            }
            await Promise.all(updatePromises);
        }, { maxWait: 5000, timeout: 20000 });

        revalidatePath(`/admin/payments`);
        revalidatePath(`/admin/payments/${enrollmentId}`);

        return { success: true, restoredMonths, lockedMonths };
    } catch (error: any) {
        console.error('restoreMonthlyFeeAmount error:', error);
        return { success: false, error: error.message };
    }
}

export async function cancelPayment(paymentId: string) {
    try {
        const payment = await prisma.payment.findUnique({
            where: { id: paymentId },
            include: {
                monthlyFeeInstance: { include: { payments: true } },
                miscFee: { include: { payments: true } },
                bookInstance: { include: { payments: true } }
            }
        });

        if (!payment) {
            return { success: false, error: "Payment not found." };
        }

        await prisma.$transaction(async (tx) => {
            // Delete the payment
            await tx.payment.delete({
                where: { id: paymentId }
            });

            // Recalculate statuses
            if (payment.monthlyFeeInstance) {
                const remainingPayments = payment.monthlyFeeInstance.payments.filter(p => p.id !== paymentId);
                const totalPaid = remainingPayments.reduce((sum, p) => sum + p.amountPaid, 0);
                const amountDue = payment.monthlyFeeInstance.amountDue;

                let newStatus = 'UNPAID';
                if (totalPaid >= amountDue && amountDue > 0) newStatus = 'PAID';
                else if (totalPaid > 0) newStatus = 'PARTIAL';

                // Keep WAIVED if fully paid off originally but then dropped to 0 and was explicitly waived
                if ((payment.monthlyFeeInstance as any).status === 'WAIVED') {
                    if (totalPaid === 0 && (payment.monthlyFeeInstance as any).adjustmentType === 'WAIVE') {
                        newStatus = 'WAIVED';
                    }
                }

                await tx.monthlyFeeInstance.update({
                    where: { id: payment.monthlyFeeInstance.id },
                    data: { status: newStatus as any }
                });
            } else if (payment.miscFee) {
                const remainingPayments = payment.miscFee.payments.filter(p => p.id !== paymentId);
                const totalPaid = remainingPayments.reduce((sum, p) => sum + p.amountPaid, 0);
                const amountDue = payment.miscFee.amountDue;

                let newStatus = 'UNPAID';
                if (totalPaid >= amountDue && amountDue > 0) newStatus = 'PAID';
                else if (totalPaid > 0) newStatus = 'PARTIAL';

                await tx.miscFee.update({
                    where: { id: payment.miscFee.id },
                    data: { status: newStatus as any }
                });
            } else if (payment.bookInstance) {
                const remainingPayments = payment.bookInstance.payments.filter(p => p.id !== paymentId);
                const totalPaid = remainingPayments.reduce((sum, p) => sum + p.amountPaid, 0);
                const amountDue = payment.bookInstance.amountDue;

                let newStatus = 'UNPAID';
                if (totalPaid >= amountDue && amountDue > 0) newStatus = 'PAID';
                else if (totalPaid > 0) newStatus = 'PARTIAL';

                await tx.bookInstance.update({
                    where: { id: payment.bookInstance.id },
                    data: { status: newStatus as any }
                });
            }
        });

        revalidatePath(`/admin/payments`);
        revalidatePath(`/admin/payments/${payment.enrollmentId}`);

        return { success: true };
    } catch (error: any) {
        console.error('cancelPayment error:', error);
        return { success: false, error: error.message };
    }
}

export async function deleteMiscFee(miscFeeId: string) {
    try {
        const miscFee = await prisma.miscFee.findUnique({
            where: { id: miscFeeId },
            include: { payments: true }
        });

        if (!miscFee) {
            return { success: false, error: "Miscellaneous fee not found." };
        }

        if (miscFee.status !== 'UNPAID' || miscFee.payments.length > 0) {
            return { success: false, error: "Cannot delete a fee that already has payments recorded. Cancel the payments first." };
        }

        await prisma.miscFee.delete({
            where: { id: miscFeeId }
        });

        revalidatePath(`/admin/payments`);
        revalidatePath(`/admin/payments/${miscFee.enrollmentId}`);

        return { success: true };
    } catch (error: any) {
        console.error('deleteMiscFee error:', error);
        return { success: false, error: error.message };
    }
}
